title: Avatar
author: Paul Radzkov
email: radzkov@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Userpic Paul Radzkov
# twitter_username: paulradzkov
github_username: paulradzkov
google_analytics: UA-29416794-1
remote_theme: paulradzkov/docs-template
github_link: https://github.com/paulradzkov/avatar
